/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as EntriesRouteImport } from './routes/entries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntriesIdRouteImport } from './routes/entries.$id'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdRoute = EntriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EntriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entries': typeof EntriesRouteWithChildren
  '/new': typeof NewRoute
  '/entries/$id': typeof EntriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entries': typeof EntriesRouteWithChildren
  '/new': typeof NewRoute
  '/entries/$id': typeof EntriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entries': typeof EntriesRouteWithChildren
  '/new': typeof NewRoute
  '/entries/$id': typeof EntriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entries' | '/new' | '/entries/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entries' | '/new' | '/entries/$id'
  id: '__root__' | '/' | '/entries' | '/new' | '/entries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntriesRoute: typeof EntriesRouteWithChildren
  NewRoute: typeof NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdRouteImport
      parentRoute: typeof EntriesRoute
    }
  }
}

interface EntriesRouteChildren {
  EntriesIdRoute: typeof EntriesIdRoute
}

const EntriesRouteChildren: EntriesRouteChildren = {
  EntriesIdRoute: EntriesIdRoute,
}

const EntriesRouteWithChildren =
  EntriesRoute._addFileChildren(EntriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntriesRoute: EntriesRouteWithChildren,
  NewRoute: NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
